{
  "timestamp": "2025-07-15T11:50:10.263063",
  "systems": {
    "rddl": {
      "accessible": false
    },
    "jira": {
      "accessible": false
    },
    "apj": {
      "accessible": false,
      "error": "HTTPSConnectionPool(host='apj.infineon.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002BA9F2D6C10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))",
      "url": "https://apj.infineon.com"
    },
    "des": {
      "accessible": false,
      "error": "HTTPSConnectionPool(host='des.infineon.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002BA9F2D6E90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))",
      "url": "https://des.infineon.com"
    },
    "ipstore": {
      "accessible": false,
      "error": "HTTPSConnectionPool(host='ipstore.infineon.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002BA9F2D74D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))",
      "url": "https://ipstore.infineon.com"
    },
    "svn": {
      "accessible": false,
      "error": "HTTPSConnectionPool(host='svn.infineon.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002BA9F2D6E90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))",
      "url": "https://svn.infineon.com"
    },
    "subversion": {
      "accessible": false,
      "error": "HTTPSConnectionPool(host='subversion.infineon.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002BA9F2D6710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))",
      "url": "https://subversion.infineon.com"
    }
  }
}